### ISSUE TITLE
Production Caching Issue

### ISSUE THREAD

**Issue by ebetron** [Code4PuertoRico/cfpr-website#26]
There seems to be an issue with production caching. Wondering if we can possibly blow up the project on netlify and rebuild. 

It happens mostly with the intial navbar. When you land on https://www.code4puertorico.org/ you'll notice that the navbar links are out of whack. Then if you click on any of the links, when the DOM refreshes, the navbar is fine. For some reason its only when the page initially loads that an old version of the navbar is preserved somewhere and it seems to be at the app level. 

@jpadilla Wondering if there is a cache folder created in production that we can blow up and redeploy to possibly solve the issue.

**Comment by jpadilla** [comment]
https://github.com/Code4PuertoRico/cfpr-website/pull/23 fixes the root cause
