### ISSUE TITLE
Styling Engine

### ISSUE THREAD

**Issue by ebetron** [Code4PuertoRico/cfpr-website#9]
During the 4/13 Hack Night, we were discussing which Styling Engine we would use for the site.

Options: 

- Tailwind CSS 
- Styled Components 
- [any other suggestions from the team]

**Comment by jamesxv7** [comment]
I'm full-in with Tailwind CSS, documentation is very rich from both sides:
 
- https://tailwindcss.com/docs/guides/gatsby
- https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/

**Comment by froi** [comment]
Closing this issue out. We've implemented tailwind in a base Gatsby site with a couple of placeholders.
